version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: wellbot:0.1
    command: npm run dev
    env_file:
      - .env
    volumes:
      - .:/app/
      - nodemodules:/app/node_modules

volumes:
  nodemodules: {}
